# Generated by Django 2.2 on 2019-11-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstaCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEsci', models.CharField(max_length=50, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEtni', models.CharField(max_length=50, verbose_name='Grupo Etnico')),
            ],
            options={
                'verbose_name': 'Grupo Etnico',
                'verbose_name_plural': 'Grupos Etnicos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTipo', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoEstu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiEs', models.CharField(max_length=50, verbose_name='Tipo de Estudiante')),
            ],
            options={
                'verbose_name': 'Tipo de Estudiante',
                'verbose_name_plural': 'Tipos de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='TipoLogr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiLo', models.CharField(max_length=50, verbose_name='Tipo de Logro')),
            ],
            options={
                'verbose_name': 'Tipo de Logro',
                'verbose_name_plural': 'Tipos de Logros',
            },
        ),
    ]
