# Generated by Django 2.2 on 2019-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEmpl', models.CharField(max_length=50, verbose_name='Tipo de Empleo')),
            ],
            options={
                'verbose_name': 'Tipo de Empleo',
                'verbose_name_plural': 'Tipos de Empleos',
            },
        ),
    ]
